//go:build ignore
// +build ignore

package main

import "fmt"

func main() {
	fmt.Println("package ma0")
	fmt.Println()
	fmt.Println("// Code generated by gen_full.go; DO NOT EDIT.")
	fmt.Println("// MA0Full は ma0 テーブルの全155フィールドを1:1マッピングした構造体です")
	fmt.Println("type MA0Full struct {")
	// 0～154 のフィールドを MA000～MA154 として出力
	for i := 0; i <= 154; i++ {
		fmt.Printf("    MA%03d string\n", i)
	}
	fmt.Println("}")
}
